name: gsoc-data-event-processor

services:
  gsoc-data-event-processor:
    build:
      context: ..
      dockerfile: deploy/Dockerfile
    container_name: gsoc-data-event-processor
    restart: unless-stopped
    network_mode: host
    labels:
      app: gsoc-data-event-processor
